### PR TITLE
Client updates and new Server API

### PR DESCRIPTION
**Pull request by mdavidsaver**
This work is getting close to completion.  There is a lot here, and I'll be using this PR to hold my remaining TODO list.

Until this is merged I'll be publishing the generated documentation from the 'devel' branch at https://mdavidsaver.github.io/p4p-dev/

### CODE REVIEW

**Comment by mdavidsaver** [comment]
TODO

- [ ] Server API
  - [x] Wrapper ```pvas::*``` classes: StaticProvider, DynamicProvider, ShardPV, and Operation
  - [x] Provide callback based API ```p4p.server.raw```
  - [x] Provide threaded, asyncio, and cothread wrappers
  - [x] NT type wrap/unwrap hooks
  - [x] RPC helper changed to use DynamicProvider
  - [ ] use RPC helpers in StaticProvider
  - [ ] Test cases.  Some basics, but need more.
  - [ ] Update documentation
- [ ] Client API
  - [x] Replace use of low-level ```epics::pvAccess::ChannelProvider``` with ```pvac::ClientProvider``` and friends.
  - [x] Fill out ```p4p.client.raw``` enough to be separately useful
  - [x] Update ```p4p.client.thread``` wrapper
  - [ ] Add asyncio and cothread wrapper
  - [ ] Update handling of NTEnum during put.  Allow NTEnum as sub-structure.
  - [ ] Update documentation
- [ ] [pypi.org](https://pypi.org/project/p4p/)
  - [x] Publish builds for Linux 32/64, py 2.7, 3.4, 3.5, and 3.6.
  - [ ] Publish windows build
  - [ ] Publish OSX build

**Comment by mdavidsaver** [comment]
Incompatible API changes

- Server Provider interface has changed.  Use of one of the *Provider classes and SharedPV class is now mandatory.  Also, the rpc() operation argument list has changed to accept an instance of ServerOperation, which can be used to access the argument Value, pvRequest, and other information.  (note: the high level RPC server interface has not changed)

**Comment by thomascobb** [comment]
Occasionally I get the following:

`Orphaned server message 1 : not a channel request`

Not sure what triggers it...

**Comment by mdavidsaver** [comment]
> Not sure what triggers it...

Are you seeing this with the pypi build, or otherwise with the latest pvAccessCPP?  I had thought that I'd made this message go away.

The short version is that it is/was a pvAccessCPP bug, which is annoying but innocuous.  The full story can be found on https://github.com/epics-base/pvAccessCPP/issues/97

When running the P4P unittests, and if you trigger timeouts, you should also be prepared to see

>  exception caught while in receiveThread at ../../src/remote/codec.cpp:1144: IntrospectionRegistry miss.

which is a symptom of https://github.com/epics-base/pvAccessCPP/issues/103

**Comment by thomascobb** [comment]
With these pypi versions:

epicscorelibs==7.0.1.99.1a11
p4p==1.1a20

**Comment by thomascobb** [comment]
This version of p4p fixed my context.put("TESTCOUNTER.counter", 5, "value") issue, however I can't make context.put("TESTCOUNTER", 5, "counter.value") work like I did in the original hack:

https://github.com/mdavidsaver/p4p/pull/14/files/98494fcc16514061fa541420b801682b6bd4c08a#diff-55d0fc661830274fe778c2a71ee5ef6eR353

How would I do this properly?

**Comment by thomascobb** [comment]
Ok, answered my own question:
```python
        def put_value_5(V):
            V.counter.value = 5
        self.ctxt.put("TESTCOUNTER", put_value_5, "counter.value")
```

**Comment by thomascobb** [comment]
Is that the way you intended it to work?

**Comment by thomascobb** [comment]
Next question, I monitor a big structure, the first update gives me everything as changed. I then do a Put, and a couple of fields update. I get a second update, I'm expecting it only to mark the fields that have changed as changed, but I get them all. Is this expected?

**Comment by thomascobb** [comment]
Ok, all but 4 tests are now working as expected (the 4 that include the field pvRequest in get and monitor), so here's the code:

Server:
https://github.com/dls-controls/pymalcolm/blob/p4p/malcolm/modules/pva/controllers/pvaservercomms.py

Tests:
https://github.com/dls-controls/pymalcolm/blob/p4p/tests/test_modules/test_pva/test_system_pva.py

**Comment by mdavidsaver** [comment]
> Is that the way you intended it to work?

I certainly intended that this should work, and it will continue to do so.   Using a Value builder callback in this manner is supposed to be a fallback for when it is necessary to inspect the Value to decide on how to store a python value.  The use of a callback can be avoided in this case with:

```python
self.ctxt.put("TESTCOUNTER", {'counter.value':5})
```

FYI. the default builder logic now resides in p4p.client.raw

https://github.com/mdavidsaver/p4p/blob/4dc0d6602694d478cfd956dc216b6ceee687143c/src/p4p/client/raw.py#L93-L102

This shows that

```python
context.put("TESTCOUNTER.counter", 5, "counter.value")
```

is a shorthand for

```python
context.put("TESTCOUNTER.counter", {"value": 5}, request="counter.value")
```

I think I see the confusion.  The pvRequest does not, and never would, do what you expect it to do.  What you're seeing is a decision on my part to special case what I think will be the most common case, writing only '.value'.

This confusion was compounded by the old argument stack behavior of 'pvput'.

```sh
pvput -r "counter.value" TESTCOUNTER 5
```

Worked not because 'counter.value' was addressing a sub-structure, but because it was the first, and only, non-Structure Field.  When the 'pvput' code recursed through the Structure, it "poped" the 5 into 'counter.value'.

The new behavior of 'pvput' will force you make this explicit regardless of server behavior.

```sh
pvput TESTCOUNTER counter.value=5
```

The '-r "counter.value"' may be omitted because the default request is now "field()" (aka. select all).

**Comment by mdavidsaver** [comment]
In P4P-speak, the old behavior of the pvget CLI tool would be something like:

```python
def builder(args, value):
    for fldname in value:
        subf = value[fldname]
        if isinstance(subf, Value):
            builder(args, subf)
        elif isinstance(subf, numpy.ndarray):
            nelem = int(args.pop(0))
            arr = []
            for _i in range(nelem):
                arr.append(args.pop(0))
            value[fldname] = numpy.asarray(arr)
        else:
            value[fldname] = args.pop(0)

ctxt.put(pvname, builder=functools.partial(builder, sys.argv), ...)
```

**Comment by thomascobb** [comment]
I still need the pvRequest though `self.ctxt.put("TESTCOUNTER", {'counter.value':5}, "counter.value")` does the trick

**Comment by thomascobb** [comment]
Ok, so only the handling of monitor/get on subfields, the Handler stub baseclass, and PEP8 left then. I'm off now, have a good weekend

**Comment by mdavidsaver** [comment]
> I still need the pvRequest though self.ctxt.put("TESTCOUNTER", {'counter.value':5}, "counter.value") does the trick

I'd be interested to know if ```self.ctxt.put("TESTCOUNTER", {'counter.value':5}, "field()")``` also works.  My intent is that passing ```request=None``` should be the same as ```request="field()"```.

**Comment by mdavidsaver** [comment]
> Orphaned server message 1 : not a channel request

I saw it again myself, so that issue is not so fixed after all...

**Comment by mdavidsaver** [comment]
> only the handling of monitor/get on subfields, the Handler stub baseclass, and PEP8 left

I have something on all three points: mask/filter of fields in Get and Monitor updates, ```p4p.server.*.Handler```, and I ran [autopep8](https://pypi.python.org/pypi/autopep8/) which gets some of the style issues.

A new pypi build 1.1a24 is available.

**Comment by thomascobb** [comment]
I get a segfault now

```
$ python
Python 2.7.3 (default, Nov  9 2013, 21:59:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> from p4p import Value
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tmc43/virtualenvs/pymalcolm/lib/python2.7/site-packages/p4p/__init__.py", line 18, in <module>
    from .wrapper import Value, Type
  File "/home/tmc43/virtualenvs/pymalcolm/lib/python2.7/site-packages/p4p/wrapper.py", line 2, in <module>
    from ._p4p import (Type as _Type, Value as _Value)
ImportError: numpy.core.multiarray failed to import
>>> import numpy
>>> from p4p import Value
Segmentation fault
$ gdb python
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-110.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/tmc43/virtualenvs/pymalcolm/bin/python...done.
(gdb) run
Starting program: /home/tmc43/virtualenvs/pymalcolm/bin/python 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Python 2.7.3 (default, Nov  9 2013, 21:59:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> from p4p import Value
Detaching after fork from child process 3972.
Detaching after fork from child process 3974.
[New Thread 0x7fffe84c5700 (LWP 3991)]
[Thread 0x7fffe84c5700 (LWP 3991) exited]
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tmc43/virtualenvs/pymalcolm/lib/python2.7/site-packages/p4p/__init__.py", line 18, in <module>
    from .wrapper import Value, Type
  File "/home/tmc43/virtualenvs/pymalcolm/lib/python2.7/site-packages/p4p/wrapper.py", line 2, in <module>
    from ._p4p import (Type as _Type, Value as _Value)
ImportError: numpy.core.multiarray failed to import
>>> import numpy
>>> from p4p import Value

Program received signal SIGSEGV, Segmentation fault.
PyObject_Malloc (nbytes=50) at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Objects/obmalloc.c:788
788	            if ((pool->freeblock = *(block **)bp) != NULL) {
Missing separate debuginfos, use: debuginfo-install blas-3.4.2-8.el7.x86_64 glibc-2.17-222.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-19.el7.x86_64 lapack-3.4.2-8.el7.x86_64 libcom_err-1.42.9-12.el7_5.x86_64 libgcc-4.8.5-28.el7_5.1.x86_64 libgfortran-4.8.5-28.el7_5.1.x86_64 libquadmath-4.8.5-28.el7_5.1.x86_64 libselinux-2.5-12.el7.x86_64 libstdc++-4.8.5-28.el7_5.1.x86_64 ncurses-libs-5.9-14.20130511.el7_4.x86_64 nss-softokn-freebl-3.36.0-5.el7_5.x86_64 openssl-libs-1.0.2k-12.el7.x86_64 pcre-8.32-17.el7.x86_64 readline-6.2-10.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  PyObject_Malloc (nbytes=50)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Objects/obmalloc.c:788
#1  0x00007ffff7a993fa in PyString_FromStringAndSize (str=0x0, size=13)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Objects/stringobject.c:88
#2  0x00007ffff7b0b5da in r_object (p=0x7fffffff4c70)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/marshal.c:803
#3  0x00007ffff7b0beb6 in r_object (p=0x7fffffff4c70)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/marshal.c:1010
#4  0x00007ffff7b0bd65 in r_object (p=0x7fffffff4c70)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/marshal.c:880
#5  0x00007ffff7b0becc in r_object (p=0x7fffffff4c70)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/marshal.c:1013
#6  0x00007ffff7b0ca08 in PyMarshal_ReadObjectFromString (str=<optimized out>, len=<optimized out>)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/marshal.c:1181
#7  0x00007ffff7b0cb2f in PyMarshal_ReadLastObjectFromFile (fp=<optimized out>)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/marshal.c:1142
#8  0x00007ffff7b0873c in read_compiled_module (fp=0xccc6f0, 
    cpathname=0x7fffffff4db0 "/home/tmc43/virtualenvs/pymalcolm/lib/python2.7/site-packages/p4p/wrapper.pyc")
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/import.c:773
#9  load_source_module (name=0x7fffffff6f90 "p4p.wrapper", 
    pathname=0x7fffffff5ec0 "/home/tmc43/virtualenvs/pymalcolm/lib/python2.7/site-packages/p4p/wrapper.py", 
    fp=0xccc4b0) at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/import.c:994
#10 0x00007ffff7b0943f in import_submodule (mod=0x7ffff7e951a0, subname=0x7fffffff6f94 "wrapper", 
    fullname=0x7fffffff6f90 "p4p.wrapper")
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/import.c:2595
#11 0x00007ffff7b096d4 in load_next (mod=0x7ffff7e951a0, altmod=0x7ffff7e951a0, p_name=<optimized out>, 
    buf=0x7fffffff6f90 "p4p.wrapper", p_buflen=0x7fffffff7f98)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/import.c:2415
#12 0x00007ffff7b09d00 in import_module_level (name=0x0, globals=<optimized out>, locals=<optimized out>, 
    fromlist=0xc73f80, level=<optimized out>)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/import.c:2136
#13 0x00007ffff7b0a244 in PyImport_ImportModuleLevel (name=0x7ffff7e46354 "wrapper", globals=0xcae160, 
    locals=0xcae160, fromlist=0xc73f80, level=<optimized out>)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/import.c:2188
#14 0x00007ffff7aec0ef in builtin___import__ (self=<optimized out>, args=<optimized out>, kwds=<optimized out>)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/bltinmodule.c:49
#15 0x00007ffff7a44e13 in PyObject_Call (func=0x7ffff7fb1dd0, arg=<optimized out>, kw=<optimized out>)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Objects/abstract.c:2529
#16 0x00007ffff7aec5d3 in PyEval_CallObjectWithKeywords (func=0x7ffff7fb1dd0, arg=0xc1f410, kw=<optimized out>)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/ceval.c:3890
#17 0x00007ffff7af0a96 in PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/ceval.c:2333
#18 0x00007ffff7af495e in PyEval_EvalCodeEx (co=0xc81eb0, globals=<optimized out>, locals=<optimized out>, 
    args=<optimized out>, argcount=0, kws=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/ceval.c:3253
#19 0x00007ffff7af4a72 in PyEval_EvalCode (co=<optimized out>, globals=<optimized out>, locals=<optimized out>)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/ceval.c:667
#20 0x00007ffff7b05d62 in PyImport_ExecCodeModuleEx (name=0x7fffffffb5c0 "p4p", co=0xc81eb0, 
    pathname=0x7fffffff8390 "/home/tmc43/virtualenvs/pymalcolm/lib/python2.7/site-packages/p4p/__init__.pyc")
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/import.c:681
#21 0x00007ffff7b0862e in load_source_module (name=0x7fffffffb5c0 "p4p", 
    pathname=0x7fffffff8390 "/home/tmc43/virtualenvs/pymalcolm/lib/python2.7/site-packages/p4p/__init__.pyc", 
    fp=<optimized out>) at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/import.c:1018
#22 0x00007ffff7b08e8d in load_package (name=0x7fffffffb5c0 "p4p", pathname=<optimized out>)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/import.c:1074
#23 0x00007ffff7b0943f in import_submodule (mod=0x7ffff7da5430 <_Py_NoneStruct>, subname=0x7fffffffb5c0 "p4p", 
    fullname=0x7fffffffb5c0 "p4p")
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/import.c:2595
#24 0x00007ffff7b096d4 in load_next (mod=0x7ffff7da5430 <_Py_NoneStruct>, altmod=0x7ffff7da5430 <_Py_NoneStruct>, 
    p_name=<optimized out>, buf=0x7fffffffb5c0 "p4p", p_buflen=0x7fffffffc5c8)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/import.c:2415
#25 0x00007ffff7b09d00 in import_module_level (name=0x0, globals=<optimized out>, locals=<optimized out>, 
    fromlist=0xc98ad0, level=<optimized out>)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/import.c:2136
---Type <return> to continue, or q <return> to quit---
#26 0x00007ffff7b0a244 in PyImport_ImportModuleLevel (name=0xbf79b4 "p4p", globals=0x640160, locals=0x640160, 
    fromlist=0xc98ad0, level=<optimized out>)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/import.c:2188
#27 0x00007ffff7aec0ef in builtin___import__ (self=<optimized out>, args=<optimized out>, kwds=<optimized out>)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/bltinmodule.c:49
#28 0x00007ffff7a44e13 in PyObject_Call (func=0x7ffff7fb1dd0, arg=<optimized out>, kw=<optimized out>)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Objects/abstract.c:2529
#29 0x00007ffff7aec5d3 in PyEval_CallObjectWithKeywords (func=0x7ffff7fb1dd0, arg=0x7ffff7f5b050, kw=<optimized out>)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/ceval.c:3890
#30 0x00007ffff7af0a96 in PyEval_EvalFrameEx (f=<optimized out>, throwflag=<optimized out>)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/ceval.c:2333
#31 0x00007ffff7af495e in PyEval_EvalCodeEx (co=0xc81e30, globals=<optimized out>, locals=<optimized out>, 
    args=<optimized out>, argcount=0, kws=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/ceval.c:3253
#32 0x00007ffff7af4a72 in PyEval_EvalCode (co=<optimized out>, globals=<optimized out>, locals=<optimized out>)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/ceval.c:667
#33 0x00007ffff7b14185 in run_mod (arena=0x67c910, flags=0x7fffffffcb00, locals=0x640160, globals=0x640160, 
    filename=0x7ffff7b5e6df "<stdin>", mod=0x6bc140)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/pythonrun.c:1353
#34 PyRun_InteractiveOneFlags (fp=<optimized out>, filename=0x7ffff7b5e6df "<stdin>", flags=0x7fffffffcb00)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/pythonrun.c:852
#35 0x00007ffff7b1439e in PyRun_InteractiveLoopFlags (fp=0x7ffff70d3640 <_IO_2_1_stdin_>, 
    filename=0x7ffff7b5e6df "<stdin>", flags=0x7fffffffcb00)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/pythonrun.c:772
#36 0x00007ffff7b14a9c in PyRun_AnyFileExFlags (fp=0x7ffff70d3640 <_IO_2_1_stdin_>, 
    filename=0x7ffff7b5e6df "<stdin>", closeit=0, flags=0x7fffffffcb00)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Python/pythonrun.c:741
#37 0x00007ffff7b2a12c in Py_Main (argc=<optimized out>, argv=<optimized out>)
    at /dls_sw/prod/tools/RHEL6-x86_64/Python/2-7-3/src/Python-2.7.3/Modules/main.c:639
#38 0x00007ffff6d2e3d5 in __libc_start_main () from /lib64/libc.so.6
#39 0x0000000000400679 in _start ()
(gdb) 
```

**Comment by mdavidsaver** [comment]
> RuntimeError: module compiled against API version 0xc but this version of
numpy is 0xa

What numpy version do you have?

**Comment by thomascobb** [comment]
An old one, numpy==1.11.1

**Comment by thomascobb** [comment]
I'm testing against that because that's what we use in production

**Comment by thomascobb** [comment]
Related discussion here:
https://github.com/numpy/numpy/issues/5888

**Comment by mdavidsaver** [comment]
I have travis-ci builds against numpy==1.8.2 (circa debian 8) so 1.11.1 is within the range of source versions that P4P supports.  The nice list at:

https://github.com/numpy/numpy/blob/master/numpy/core/setup_common.py#L12

seems to say that ABI forward compatibility may be possible from 1.7.x through the present 1.15.x.  I'll switch the pypi build back to numpy==1.8.2 and we will see how well this works.

**Comment by mdavidsaver** [comment]
pypi build p4p==1.1a25 is available.  This is build against numpy==1.8.2, and I was able to successfully run the p4p unittests with numpy==1.14.5

**Comment by thomascobb** [comment]
Stub Handler looks good. Could I have a DynamicHandler stub too please?

Numpy build has fixed the segfault problems too, but the get/monitor of subfields doesn't work as I expect:

```
$ pvget TESTCOUNTER.meta -r fields
TESTCOUNTER.meta
malcolm:core/BlockMeta:1.0 
    string description 
    string[] tags []
    boolean writeable false
    string label 
    string[] fields [health,counter,zero,increment]
```
While I was expecting this:
```
$ pvget TESTCOUNTER.meta -r fields
TESTCOUNTER.meta
malcolm:core/BlockMeta:1.0 
    string[] fields [health,counter,zero,increment]
```
Did I misunderstand something? Do I have to do something on the server side or does SharedPV wrap up the subfield part of it for me?

**Comment by mdavidsaver** [comment]
> Did I misunderstand something?

Nope, this is the big difference which has caused all the fuss.  What ```pvget``` isn't showing you is the 'changed' mask, which will only include 'fields' in your example.

**Comment by thomascobb** [comment]
So what is going over the wire? The full structure, but then only a subset of the field values?

**Comment by mdavidsaver** [comment]
Only a subset.  At a low level, the changed mask which comes along with the Get is used in the (de)serialization step.

**Comment by mdavidsaver** [comment]
> The full structure, but then only a subset of the field values?

I should just say, yes.  This is what happens.

**Comment by thomascobb** [comment]
- [ ] At the moment I do ```for name, spec in v.type().aspy()[2]```, need something that doesn't have a 2 in it

**Comment by mdavidsaver** [comment]
It turns out that ```v.type().aspy()[2]``` can already be spelled ```v.type().items()```.

It won't be possible to pass ```{}``` to rpc() unless I add code which infers Type from an arbitrary python object.  This is something I've avoided doing as it isn't so clear to me how this should be done.  Instead 7e69f5d805b7c5ebc5ac481e4a7ad17624299c1a allows passing None as a shorthand for ```Value(Type([]))``` (which I recall was your original suggestion...).

**Comment by thomascobb** [comment]
Now that rpc supports value=None, can we make that the default?

**Comment by mdavidsaver** [comment]
> I pushed to the wrong branch which erroneously merged this PR (oops)

Intentionally pushed this time.

**Pull request merged**
